### PR TITLE
Update to 2.0.8

### PR DESCRIPTION
**Pull request by Croydon**
Let's see what the CI is saying, but who knows, maybe it is this easy for once?

Edit: Be careful now to merge into stable/2.0.7 branch.

### CODE REVIEW

**Comment by uilianries** [comment]
I just moved you PR to testing/2.0.8 (new branch from testing/2.0.7)

**Comment by Croydon** [comment]
I believe stable/2.0.7 would have been the better choice as testing/2.0.7 seems to contain irrelevant testing commits

**Comment by uilianries** [comment]
Yeah stable/2.0.7 looks better, but we have a development flow to follow.

**Comment by Croydon** [comment]
This fails right now because of missing packages for some configurations of libiconv/1.15@bincrafters/stable.

I'm neither familar with your workflow in such cases nor with your package tools.  Do you want to make changes to the libiconv repository to build for these missing configurations or can I somewhere in your package tools change the Conan build policy to missing?

**Comment by uilianries** [comment]
No problem, I'll take this.

**Pull request merged**
