### PR TITLE
Can pick whether to use conan or system variant of most dependencies

### PR DESCRIPTION
**Pull request by ltjax**
After you moved those system dependencies to conan, my game did not run anymore. I think most of these are "driver" level, specifically build for the end-users computer, or in the case of OpenGL, there's even completely different libraries conforming to the same ABI (e.g. closed-source NVidia drivers vs. mesa).
I've added options switch between the system or conan variants, so everyone can be happy.

### CODE REVIEW

**Review by Croydon — CHANGES_REQUESTED** [review]
If you switch the default values to `conan` I will accept this as a temporary fix to this indeed messy situation

The mid and long-term solution will probably be a switch between virtual packages (Conan packages which install `system_requirements()`) and an actual Conan package. Or within in the respective package (e.g. mesa) a switch.

**Comment by ltjax** [comment]
> If you switch the default values to `conan` I will accept this as a temporary fix to this indeed messy situation

Any way I might convince you that this is a bad idea? Bundling tools, e.g. https://github.com/linuxdeploy/linuxdeploy, exclude most of those for a reason. See https://raw.githubusercontent.com/probonopd/AppImages/master/excludelist
I was trying to set the sensible default to the one that is useful to most users.

> 
> The mid and long-term solution will probably be a switch between virtual packages (Conan packages which install `system_requirements()`) and an actual Conan package. Or within in the respective package (e.g. mesa) a switch.

Let me quote RFC 1925 for this: "It is easier to move a problem around (for example, by moving the problem to a different part of the overall network architecture) than it is to solve it.".
The better solution here, in my opinion, is for the end-application developer to draw a clear line which "low-level" libraries are expected on their end users system for each deployable. The consequence for conan packages would be to allow to configure them into this state. If you add "virtual packages" for this, you just take away some of that configurability. e.g. you disallow different switches in "diamond like" dependency hierarchies.

**Comment by Croydon** [comment]
The virtual package for OpenGL, X11 and Wayland should also support using whatever your system provides. So I guess you might be happy with this solution eventually too. We probably need this for more stuff too, but when introduced we really should be sure that it is required.

We continuously have problems with `system_packages` and we want to get rid of them as much as possible. CCI disallows them by default and there will be soon a whitelist for virtual packages of dependencies where it is required. You can follow this discussion in tons over tons of issues, but the most relevant is currently here: https://github.com/conan-io/conan-center-index/issues/641

The approach in this pull request can be just a temporary fix, because either we don't need `system_requirements` or we do need them, but then they should be managed centralized in a few packages, not hundred of times in each recipe.

So yes, we are aware that the current situation is broken in many scenarios, but it was broken in other ways before too and we are working on it 😄

**Comment by ltjax** [comment]
> The virtual package for OpenGL, X11 and Wayland should also support using whatever your system provides. So I guess you might be happy with this solution eventually too. We probably need this for more stuff too, but when introduced we really should be sure that it is required.

I agree that virtual packages are a much better solution, but even then some configurability is required. The case is relatively clear for things like GL: you probably never want to  mesa and always use a virtual package that directs to the system lib. But what about ALSA? I do want to link to the system version, but you opted to depend on the conan version instead. How do virtual packages solve that?
I guess my point is that for some packages it won't be so clear whether they are system requirements or not. Yes, that's mostly a deployment problem, but I like to have my development environment as close as possible to that.

Either way, I don't see why "conan" is a better default unless you really just want to see if it builds. Even for a temporary solution. I guess that for all those libs people usually do not want to drag in the conan variants (especially since that makes the dependency graph explode!). It'd be broken by default, but with a more purist build. What good is that?
I'd say keep it at system, and use "conan" for testing when the better solution starts to take form.

Thanks for the link btw, it was an interesting read.

**Comment by Croydon** [comment]
I'm going to close this PR now

Since we have and use now `opengl/system` and `xorg/system` packages I believe the situation is already vastly better than at the point of time where the PR got created.

I agree, that it isn't always clear if packages should be system packages or regular Conan packages, but this is a general architectural decision and the general understanding is still that we are trying to avoid system packages except for some really low-level stuff. So this doesn't only apply to the SDL2 recipe, but to every single recipe from Bincrafters and the Conan Center Index.

If you still think this requires more discussion or the SDL2 recipe should get changed in some way, please open an issue in our central issue tracker in the `community` repository.

If https://github.com/bincrafters/community/pull/1298 gets accepted, the SDL2 recipe will also soon be moved to the `community` repository and this one gets archived.

**Pull request closed without merging**
